### ISSUE TITLE
效果蛮好的 ，可以参考下ChatGPT对话吗？ 

### ISSUE THREAD

**Issue by tosmart01** [qcrao/bulk-delete-chatGPT#1]

**Comment by qcrao** [comment]
- [删除 chatGPT 对话 - A ShareGPT conversation](https://sharegpt.com/c/4Xwwvyo)
- [Chrome插件批量删除对话](https://sharegpt.com/c/NX96lCE)
- [Bulk Delete ChatGPT - A ShareGPT conversation](https://sharegpt.com/c/HkdRNaZ)

因为 GPT-4 的频控，中间又新开了窗口，有点乱。下周我会整理一下，写篇文章，可以关注下：https://qcrao.com

**Comment by tosmart01** [comment]
我也通关了，批量删除，也是东拼西凑，然后chrome控制台自己调试，最后搞定了
