### ISSUE TITLE
需求功能展示

### ISSUE THREAD

**Issue by dqd1505826212** [qcrao/bulk-delete-chatGPT#15]
期望有一个删除进度。感谢楼主

**Comment by qcrao** [comment]
> 期望有一个删除进度。感谢楼主

建议不要一次删除太多对话，最好是 10 个以内。一次太多可能会触发 openai 风控。基于此，“删除进度”就不做了，用处不大。

**Comment by dqd1505826212** [comment]
好的，感谢解答
