### ISSUE TITLE
可以一键全选么？

### ISSUE THREAD

**Issue by Cyiming** [qcrao/bulk-delete-chatGPT#16]
我账号被盗了 太多对话了 一个个勾选太慢了

如果避免风控 可以勾选后 一次性删10个 然后间隔多少秒后删下一组

**Comment by Cyiming** [comment]
> 我账号被盗了 太多对话了 一组组勾选太慢了

能不能先不断自动下拉给所有的对话加复选框 然后全选 删除 
> 
> 如果避免风控 可以勾选后 一次性删10个 然后间隔多少秒后删下一组

**Comment by qcrao** [comment]
有两种方式：
1. 先选中不想删除的对话，然后点 toggle checkbox 这个键，这个可以反转选中状态。
2. 把你不想删除的对话 archive 掉，然后用官方自带的删除所有对话功能。（这个我没试，不知道会不会删除 archive 的对话）
