### ISSUE TITLE
Reuploading to Chrome Store

### ISSUE THREAD

**Issue by Joenahm1937** [qcrao/bulk-delete-chatGPT#18]
Hey there! Thanks for your work on this extension! 

Would you be able to upload the latest updates to the Chrome Extension Store? It seems the change I added to load globals prior to other content scripts has not been uploaded yet. I attached a screenshot of the globals.js page I see after re-installing the extension from the store. Without this fix, the extension will not work upon installation. 

<img width="829" alt="Screenshot 2024-04-15 at 3 32 23 PM" src="https://github.com/qcrao/bulk-delete-chatGPT/assets/41309544/6478e83f-63ce-4bec-abb1-199e828e059e">

**Comment by qcrao** [comment]
Of course, I'll let you know when I finished uploading. Thanks for your awesome work!

**Comment by qcrao** [comment]
@Joenahm1937 I have finished updating the extension, you can reinstall it and see if it is right version now. Thx.
