### ISSUE TITLE
Gecko compatibility

### ISSUE THREAD

**Issue by ArmynC** [qcrao/bulk-delete-chatGPT#19]
Hello! Are you interested in porting it for Firefox-side browsers?

**Comment by qcrao** [comment]
Hello! Thanks for your interest in th extension. 

Currently, I'm not familiar with porting it to Firefox and, given that there hasn't been a high demand for this feature, I don't have the resources to prioritize it at the moment. 

However, I would definitely welcome and appreciate any pull requests if you or someone else would like to contribute to adding this functionality to Firefox. Thanks again for your suggestion!
