### ISSUE TITLE
Unable to trigger the delete function

### ISSUE THREAD

**Issue by chilung-wu** [qcrao/bulk-delete-chatGPT#21]
**日期：**
2024/5/14  
今日推出GPT4o，且提供中文介面，以下操作在繁體中文頁面出現。

**環境：**
- 操作系統：Windows 11
- 版本：bulk-delete-chatGPT 4.5

**復現步驟：**
1. 選取好要刪除的對話。
2. 點擊 extension中的 'Bulk Delete' 。
3. 會自動開啟chatgpt對話框，但是無法自動點擊'刪除'。

**暫時解決方式：**
chatgpt語言切換成English(US)，extension可正常運作，應該是今日提供其他語言介面，導致非英語介面extension無法正常運作。

**截圖：**
![image](https://github.com/qcrao/bulk-delete-chatGPT/assets/90950051/1f0c2856-f3c0-4786-9608-98045d979edc)

**Comment by qcrao** [comment]
谢谢反馈。我会尽快修复

**Comment by qcrao** [comment]
@chilung-wu 已发布到 chrome store
