### ISSUE TITLE
Can you also publish for firefox?

### ISSUE THREAD

**Issue by FelixSelter** [qcrao/bulk-delete-chatGPT#22]
If I am correct for manifest v2 there is no code change required. Would be very helpful. 
Ok I tested it and you may need to update a few things. I got the error: background.service_worker is currently disabled. Apparently you  are already using manifest v3

Apparently the only thing you would need to change to publish for firefox is
```json
"background": {
    "scripts": [
       "service_worker": "background.js"
    ]
  },
```
to
```json
"background": {
    "scripts": [
      "background.js"
    ]
  },
```

Even though I get a bunch of warnings about the permissions. But the extension is working fine. You may want to take a look at this

**Comment by qcrao** [comment]
@FelixSelter I tried it, but it couldn’t run on Firefox. The expected cost of making it compatible is relatively high, so I have decided to abandon the effort. If you have a working version, please package the installer and attach it to this issue. Others who need it can install it. Thank you.

**Comment by Delicious-Bacon** [comment]
And whose extension is this? It looks like a copy of yours.

[https://addons.mozilla.org/en-US/firefox/addon/chatgpt-bulk-delete/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search](https://addons.mozilla.org/en-US/firefox/addon/chatgpt-bulk-delete/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)

**Comment by Kab00mKap0w** [comment]
@qcrao I've been using that Firefox version not knowing it was originally meant for Chrome. It has recently stopped working (Deleting instead selects "Move to Project"). So, you may see people coming here asking you to fix it.

**Comment by qcrao** [comment]
@Kab00mKap0w Thanks for the heads up. I have authorized another user to upload and maintain the Firefox Add-ons version.

Related PR / coordination thread: https://github.com/qcrao/bulk-delete-chatGPT/pull/29

Going forward, the Firefox package should be built from the shared `main` branch rather than a separate Firefox-only branch.
