### ISSUE TITLE
插件多个按钮均无效。

### ISSUE THREAD

**Issue by ZhiboWong** [qcrao/bulk-delete-chatGPT#24]
Chrome win11
remove chatboxes、toggle chatboxes、bulk delete点击后均无效果。页面也没出现任何变化。

**Comment by qcrao** [comment]
@ZhiboWong 感谢反馈。有试过卸载后重新安装吗？浏览器版本是最新的吗？

https://chromewebstore.google.com/detail/chatgpt-bulk-delete/effkgioceefcfaegehhfafjneeiabdjg?authuser=0&hl=en
