### ISSUE TITLE
Select all conversation that don't match text pattern

### ISSUE THREAD

**Issue by bennycode** [qcrao/bulk-delete-chatGPT#26]
Hi @qcrao, I really like your extension! It has helped me a lot in getting rid of unused conversations. 

An additional great feature would be the ability to select all conversations that don't include a certain pattern. For example, I've marked many conversations with "IMPORTANT" in the title. I would like to select all conversations that don't have "IMPORTANT" in their title to delete them. 

Is it possible to integrate this feature?

**Comment by qcrao** [comment]
> Hi @qcrao, I really like your extension! It has helped me a lot in getting rid of unused conversations.
>
> An additional great feature would be the ability to select all conversations that don't include a certain pattern. For example, I've marked many conversations with "IMPORTANT" in the title. I would like to select all conversations that don't have "IMPORTANT" in their title to delete them.
>
> Is it possible to integrate this feature?

Thanks for your suggestion. Based on the current implementation of the extension, it's not easy to achieve the functionality you're asking for. Additionally, this feature is not very common, so I won't be considering it for implementation at this time.
