### ISSUE TITLE
Extension Compatibility Issue After ChatGPT Website Update

### ISSUE THREAD

**Issue by heltonricardo** [qcrao/bulk-delete-chatGPT#3]
Hello, @qcrao 

I hope you're well. I wanted to report an issue: following a recent update to the ChatGPT website, the extension has stopped functioning correctly. It seems the changes on the website have disrupted the extension's ability to perform bulk conversation deletions.

**Comment by qcrao** [comment]
I've already fixed the issue and submitted it for review on the Google Chrome Store. Please wait for the latest version. Thank you!

**Comment by qcrao** [comment]
@heltonricardo Hi there,

I have released version 2.0 of the plugin and submitted it to the Chrome store. The Chrome store version is currently under review, so it might take a few days to get approved. In the meantime, you can directly install the master version from GitHub: [GitHub Link](https://github.com/qcrao/bulk-delete-chatGPT)

This new version is faster and more reliable. Please try it out and let me know how it works for you. Thank you!
