### ISSUE TITLE
Constant Loading Errors and needs a delay between each execution to not get the errors.

### ISSUE THREAD

**Issue by staplerzzz** [qcrao/bulk-delete-chatGPT#5]
Hi there,

First of all thank you for your time and making this script because it has huge potential. I just wanted to share the problems that I occurred.

If you are deleting more than 20 chats you start to get an error message pictured below.
Also you have to keep clicking delete and most of the time it only deletes 1 at a time.

The screen recorder didn't pickup the extension but anytime you see a "halt" back to the chat page I am clicking Delete again.
Here is a video of the script halting after like 5 attempts which you then you have to click Delete again (and again, etc)

_Screen Capture_: **https://github.com/qcrao/bulk-delete-chatGPT/assets/59279904/9ba37384-4dde-4e3f-aca3-ae4af60db187**

**![Screenshot 2023-09-11 005737](https://github.com/qcrao/bulk-delete-chatGPT/assets/59279904/65f7caf6-023f-4e3b-a565-350b439bc295)**
 _Also uploaded the image and video Imgur: https://imgur.com/a/OSUrV49_

**`I think an easy solution to the problem would be to add a wait-time between each delete. Even if it was 5 seconds it would make the extension much more useful. Maybe even a user input to select a delay time between each execution.`**

Kind regards!

**Comment by qcrao** [comment]
Thanks for your suggestion, I will increase the delay between deleting conversations.

**Comment by qcrao** [comment]
@staplerzzz

I have submitted the code to the master branch and submitted the new version v2.2 to the chrome web store. It may be approved tomorrow. Previously, you could delete up to 10 (or less) conversations at a time. Alternatively, you can install plugins directly from source code. Thank you, happy using it.

**Comment by qcrao** [comment]
The new version has been approved, please update the plugin. Welcome to continue to provide feedback on usage issues, thank you.

**Comment by staplerzzz** [comment]
Awesome man! Thanks for the quick work!!!
