### ISSUE TITLE
delete button stopped working

### ISSUE THREAD

**Issue by amgalitzky** [qcrao/bulk-delete-chatGPT#8]
After checking the checkboxes & trying to delete, the delete button does nothing.
I didn't check your code but If I have to guess ChatGPT changed their markup, & broke your delete button selector.

**Comment by WenceslaoRojas** [comment]
const conversationElement = await checkbox.closest('.flex.p-3.items-center.gap-3.relative.rounded-md')


This fixes the error. Esto soluciona el error. Esperemos que pronto pueda arreglarlo @qcrao

**Comment by qcrao** [comment]
Fixed. Submitting to chrome web store, thank you! @WenceslaoRojas

**Comment by amgalitzky** [comment]
@qcrao it seems like they changed stuff around again & messed it up.

**Comment by qcrao** [comment]
> @qcrao it seems like they changed stuff around again & messed it up.

I just tried it on my computer and it works. Maybe you might want to reinstall the plugin and give it a try.

**Comment by amgalitzky** [comment]
> > @qcrao it seems like they changed stuff around again & messed it up.
> 
> I just tried it on my computer and it works. Maybe you might want to reinstall the plugin and give it a try.

After reinstalling it works again. Thank You!
