### ISSUE TITLE
The extension doesn't work on the new GUI

### ISSUE THREAD

**Issue by MohammadShabib** [qcrao/bulk-delete-chatGPT#9]
ChatGPT changed the GUI recently and the extension doesn't work anymore.
When I click the Add Checkboxes nothing happens.

**Comment by qcrao** [comment]
Thanks for reminding me, I will fix it as soon as possible.

**Comment by MohammadShabib** [comment]
Fixed, check the pull requests

**Comment by qcrao** [comment]
The new version of the extension has been released in the Google Web Chrome Store, please try it out. Welcome to continue to contribute code, thank you! @MohammadShabib
